### ISSUE TITLE
problem with installing Python API using the carla-0.9.6-py3.5-linux-x86_64.egg

### ISSUE THREAD

**Issue by farahini** [OATML/carsuite#6]
1

**Comment by filangelos** [comment]
Hi @farahini,

It seems that you are using **Python 3.6** while the CARLA wheels are for Python 3.5.
Could you please confirm your Python version, e.g., by pasting the output of 
```shell
python --version
```

If you want to use Python 3.6, I recommend you follow the [official installation/build CARLA guides](https://github.com/carla-simulator/carla/tree/0.9.6). Otherwise, by switching to Python 3.5 and rerunning `easy_install` should fix the issue.

**Comment by farahini** [comment]
@filangel,

Yes, I am using Python 3.6. I will try it with 3.5 then. Thanks for the comment.
